local M = {}

-- Dummy get_diff() for diff testing
-- In the future, this structure would be generated by the Rust backend.
function M.mock_diff()
	local diff_res = {
		files = {
			["example.lua"] = {
				diffs = {
					{
						id = 1,
						start_line = 0, -- 0-based, inclusive
						end_line = 1, -- 0-based, exclusive
						new_lines = {
							"change M = {}",
						},
					},
					{
						id = 2,
						start_line = 9,
						end_line = 10,
						new_lines = {
							"change = {}",
							"change = {}",
						},
					},
				},
			},
			-- Support for multiple files
			-- ["another_file.lua"] = {
			--   {
			--     id = 3,
			--     start_line = 2,
			--     end_line = 4,
			--     new_lines = {
			--       "new code here",
			--       "another line",
			--     },
			--   },
			-- }
		},
	}

	require("ghostwrite.diff").set_batch(diff_res)
end

return M
